apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: mcitdemo.azurecr.io/ml-flask:v1
        name: nginx
      imagePullSecrets:
      - name: acrsecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    nodePort: 32000
  selector:
    app: nginx
  type: NodePort
