trigger:
- master

pool: rancher-pool

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: rancher-pool
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        targetPath: '$(Pipeline.Workspace)/manifests'
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-svc-conn'
        repository: 'mcitdemo'
        command: 'buildAndPush'
        Dockerfile: '**/app/Dockerfile'
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'rancher-connection'
        manifests: ' $(Pipeline.Workspace)/manifests/deploy.yaml'