trigger:
- master

pool: fnpool1

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: fnpool1
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-svc-conn'
        repository: 'mcitdemo'
        command: 'buildAndPush'
        Dockerfile: '**/app/Dockerfile'